name: Auto Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            sudo cd /var/www/kelas-industri/
            sudo git pull
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader
            sudo php artisan optimize
